orange/plugins/stat/stat.lua
change the server address of dashboard to server ip address without port
=> #30 dashboard server address change

.editorconfig, .gitignore
添加editorconfig文件，代码风格保持统一
添加一些ide工具的忽略，idea,eclipse
=> add editor config and some ide ignnore

conf/orange.conf, dashboard/routes/dashboard.lua, dashboard/static/js/signature_auth.js, dashboard/views/common/left_nav.html, dashboard/views/signature_auth/credential-add.html, dashboard/views/signature_auth/credential-edit.html, dashboard/views/signature_auth/credential-tmpl.html, dashboard/views/signature_auth/signature_auth.html, install/orange-v0.6.2.sql, orange/plugins/signature_auth/README.md, orange/plugins/signature_auth/api.lua, orange/plugins/signature_auth/handler.lua, orange/utils/extractor.lua
git rebase -i upstream/master
前一个 pr https://github.com/sumory/orange/pull/71
previous pr https://github.com/sumory/orange/pull/71
=> Sianature Auth

orange/plugins/signature_auth/handler.lua
fix: Correct the plug module name
=> fix: correct plugin name of `SignatureAuth`

orange/lib/globalpatches.lua, orange/plugins/common_api.lua, orange/plugins/kvstore/api.lua, orange/plugins/property_rate_limiting/counter.lua, orange/plugins/rate_limiting/counter.lua, orange/plugins/waf/handler.lua, orange/store/dao.lua, orange/store/orange_db.lua, orange/utils/config_loader.lua, orange/utils/json.lua, orange/utils/utils.lua
uniform json function call:
```
remove utils.json_encode
remove utils.json_decode
add json.encode
add json.decode
```
=> uniform json function call.

dashboard/static/js/signature_auth.js
fix: result in config sync fail
=> fix: typos

dashboard/views/property_rate_limiting.html
Fix the dashboard displays error. For the property_rate_limiting plugins has no conditions choice part, it should be  variables extractor.
=> fix: the dashboard displays error

dashboard/static/js/balancer.js
Signed-off-by: Zhao Junwang <zhjwpku@gmail.com>
=> fix balancer ui bug

orange/utils/balancer.lua
暂停全部host，再启动其中的一个host，现在的更新规则导致服务不能用。
该 patch 解决了上述问题。
Signed-off-by: Zhao Junwang <zhjwpku@gmail.com>
=> Fix balancer bug

dashboard/model/persist.lua, dashboard/routes/persist.lua, dashboard/server.lua, dashboard/static/js/persist_stat.js, dashboard/views/common/left_nav.html, dashboard/views/persist-stat.html, dashboard/views/status.html, install/orange-v0.7.0.sql, orange/plugins/persist/api.lua, orange/plugins/persist/handler.lua, orange/plugins/persist/persist.lua, orange/plugins/stat/stat.lua
- save orange stat info to mysql
- view history stat info
=> Persist log plugin

dashboard/routes/dashboard.lua, dashboard/static/js/jwt_auth.js, dashboard/views/common/left_nav.html, dashboard/views/jwt_auth/credential-add.html, dashboard/views/jwt_auth/credential-edit.html, dashboard/views/jwt_auth/credential-tmpl.html, dashboard/views/jwt_auth/jwt_auth.html, install/orange-v0.6.4.sql, orange/orange.lua, orange/plugins/divide/handler.lua, orange/plugins/jwt_auth/README.md, orange/plugins/jwt_auth/api.lua, orange/plugins/jwt_auth/handler.lua
* 项目依赖 [SkyLothar/lua-resty-jwt](https://github.com/SkyLothar/lua-resty-jwt)
* `opm get  lua-resty-jwt` 或者 `luarocks install lua-resty-jwt`
* 认证方式：
* 1、 Header `Authorization`:`Bearer Token`
* 2、 Query `token=Token`
=> add jwt plugins

dashboard/views/common/condition-add.html, dashboard/views/common/condition-edit.html, dashboard/views/common/selector-edit.html, dashboard/views/common/selector-judge-condition-part.html, orange/utils/condition.lua
现在的规则筛选是依赖HTTP报文，严重依赖http报文这可能是一个问题。如果是个随机概率筛选这样就完美了，就不用完全依赖报文去做筛选了。
=> 加个随机选项，模拟RR

conf/nginx.conf.example
proxy the websocket and http protocol at the same time
=> feat: add websocket support to the proxy server

orange/plugins/jwt_auth/README.md
=> JWT 插件安装说明

orange/plugins/jwt_auth/README.md
hotfix   jwt  plugin   
more see  https://github.com/SkyLothar/lua-resty-jwt/issues/81
=> hotfix   jwt  plugin

dashboard/views/common/condition-add.html, dashboard/views/common/condition-edit.html, dashboard/views/common/selector-edit.html, dashboard/views/common/selector-judge-condition-part.html, orange/plugins/signature_auth/handler.lua
1：支持selector 和 rule中，根据http method进行过滤；
2：在鉴权模块中，将md5和请求中带过来的值进行小写比较。（以防调用方是生成的大写的，则会鉴权不通过。）
=> 在dashboard UI层支持根据http method进行过滤和选择。

CHANGELOG.md, Makefile, README.md, README_zh.md, conf/orange.conf.example, install/orange-v0.7.0.sql, orange/plugins/kafka/README.md
根据https://github.com/sumory/orange/pull/240 中的问题进行了更正，请重点检查changelog是否齐全。
=> fix pr#240 issues

README.md, README_zh.md
=> add Contributors

README.md, conf/nginx.conf.example
=> bugfix:注释符修正

README_zh.md
=> bugfix-fix linux command

Makefile, conf/orange.conf.example, orange/plugins/rewrite/handler.lua
=> bugfix: luarocks install `api` directory does not exist.

conf/nginx.conf.example, dashboard/routes/dashboard.lua, dashboard/static/js/balancer.js, dashboard/views/balancer.html, dashboard/views/common/left_nav.html, orange/orange.lua, orange/plugins/balancer/README.md, orange/plugins/balancer/api.lua, orange/plugins/balancer/handler.lua, orange/plugins/base_handler.lua, orange/plugins/redirect/handler.lua, orange/utils/balancer.lua
=> Revert "change: remove `balancer` plugin."

install/orange-master.sql
=> change: add master branch sql file.

Makefile, README.md, README_zh.md, rockspec/orange-master-0.rockspec
=> change: rename master branch rocks file.

conf/nginx.conf.example, conf/orange.conf.example
=> change: update master branch configuration file.

conf/nginx.conf.example
=> change: `nginx.conf` default upstream add header info output.

.travis/linux_runner.sh, api/router.lua, conf/orange.conf.example, t/ORANGE.pm, t/servers/api.lua, t/servers/upstream.lua
=> change: custom `orange` unit test server config.

.travis/linux_runner.sh, t/orange/01-plugins/01-headers.t
=> test: add `headers` plugin unit test.

orange/plugins/redirect/handler.lua, t/orange/01-plugins/02-redirect.t, t/servers/upstream.lua
=> test: add `redirect` plugin unit test.

t/orange/01-plugins/01-headers.t, t/orange/01-plugins/02-redirect.t, t/orange/01-plugins/03-rewrite.t, t/servers/upstream.lua
=> test: add `rewrite` plugin unit test.

t/orange/01-plugins/04-basic_auth.t, t/servers/upstream.lua
=> test: add `basic_auth` plugin unit test.

t/orange/01-plugins/05-key_auth.t
=> test: add `key_auth` plugin unit test.

t/orange/01-plugins/06-jwt_auth.t, t/servers/upstream.lua
=> test: add `jwt_auth` plugin unit test.

t/orange/01-plugins/07-signature_auth.t
=> test: add `signature_auth` plugin unit test.

t/orange/01-plugins/08-rate_limiting.t
=> test: add `rate_limiting` plugin unit test.

t/orange/01-plugins/09-waf.t, t/servers/upstream.lua
=> test: add `waf` plugin unit test.

t/ORANGE.pm, t/orange/01-plugins/10-divide.t, t/servers/upstream.lua
=> test: added test cases for `divide` plugin.

docs/plugins/rate_limiting-cn.md, docs/plugins/rate_limiting.md, orange/plugins/rate_limiting/README.md
=> doc: added doc for `rate_limiting` plugin.

docs/plugins/signature_auth-cn.md, docs/plugins/signature_auth.md, orange/plugins/signature_auth/README.md
=> doc: added doc for `signature_auth` plugin.

docs/plugins/key_auth-cn.md, docs/plugins/key_auth.md, orange/plugins/key_auth/README.md
=> doc: added doc for `key_auth` plugin.

docs/plugins/basic_auth-cn.md, docs/plugins/basic_auth.md, orange/plugins/basic_auth/README.md
=> doc: added doc for `basic_auth` plugin.

conf/nginx.conf.example
=> fix cookie

conf/nginx.conf.example
=> nginx.conf.example 性能优化
